name: My workflow

on: push

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'zia-khan-website.surge.sh'
          project: '.'
          login: ziaukhan@hotmail.com
          token: ${{ secrets.surge_token }}